- hosts: master
  tasks:
  - name: copy deployment file to kubernetes master 
    copy:
      src: deployment.yaml
      dest: /ubuntu/
  - name: delete the previous of kubernetes objects 
    command: kubectl delete -f /ubuntu/deployment.yaml
  - name: Create a Deployment by reading the definition from a local file
    command: kubectl apply -f /ubuntu/deployment.yaml
      
