- hosts: master
  tasks:
  - name: copy deployment file to kubernetes master 
    copy:
      src: deployment.yaml
      dest: /ubuntu/deployments/
  - name: Create a Deployment by reading the definition from a local file
    command: kubectl apply -f /ubuntu/deployments/deployment.yaml
      
