apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicdsonar
spec:
  selector:
    matchLabels:
      app: dockerci
  template:
    metadata:
      labels:
        app: dockerci
    spec:
      containers:
      - name: dockerci
        image: keesarasanthosh/dockerci:docker_tag
        command: ["/bin/sh"]
        args: ["-c","sh /usr/local/tomcat/bin/startup.sh;while true; do echo hello; sleep 10;done"]
        ports:
            - name: http
              containerPort: 8080
  replicas: 2
---
apiVersion: v1
kind: Service
metadata:
  name: cicdsonar-app-service
  labels:
    app: dockerci
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 31884
    protocol: TCP
    name: http
  selector:
    app: dockerci
